"""add amount to expenses

Revision ID: 372a21ef4c60
Revises: 538b0b42bddd
Create Date: 2026-01-19 11:30:37.676177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '372a21ef4c60'
down_revision: Union[str, Sequence[str], None] = '538b0b42bddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Transaction amount'))
    op.create_index(op.f('ix_expenses_amount'), 'expenses', ['amount'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_amount'), table_name='expenses')
    op.drop_column('expenses', 'amount')
    # ### end Alembic commands ###
