"""create expenses table

Revision ID: 538b0b42bddd
Revises: 
Create Date: 2026-01-15 20:13:51.126022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538b0b42bddd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True, comment='Date on which the transaction occurred'),
    sa.Column('expense_type', sa.Enum('Income', 'Expense', name='expense_type_enum'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('transaction_type', sa.Enum('Credit', 'Debit', name='transaction_type_enum'), nullable=False),
    sa.Column('transaction_mode', sa.Enum('UPI', 'NEFT', 'IMPS', 'CASH', name='transaction_mode_enum'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('account', sa.String(length=255), nullable=False, comment='Transaction with whom'),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True, comment='Tags for grouping/filtering transactions'),
    sa.Column('comments', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_account'), 'expenses', ['account'], unique=False)
    op.create_index(op.f('ix_expenses_category'), 'expenses', ['category'], unique=False)
    op.create_index(op.f('ix_expenses_expense_type'), 'expenses', ['expense_type'], unique=False)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_transaction_mode'), 'expenses', ['transaction_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenses_transaction_mode'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_expense_type'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_account'), table_name='expenses')
    op.drop_table('expenses')
    # ### end Alembic commands ###
